// Generated by scripts/generate-auth-contracts.cjs. Do not edit.

export type CompleteGoogleAuthInput = { actor_type: "customer" | "user" | "member"; existing_token?: string | undefined; };
export type CompleteGoogleAuthResponse = {
    status: "link_required";
} | {
    status: "complete";
    token: string;
};
export type VendorSessionIssueResponse = {
    code: string;
};
export type VendorSessionConsumeResponse = {
    status: "authenticated";
    token: string;
} | {
    status: "verification_required";
    token: string;
    email: string;
};
