// Generated by scripts/generate-auth-contracts.cjs. Do not edit.

export type CompleteGoogleAuthInput = { actor_type: "customer" | "user" | "member"; existing_token?: string | undefined; };
export type CompleteGoogleAuthResponse = {
    status: "link_required";
} | {
    status: "complete";
    token: string;
};
export type GooglePanelProfileResponse = {
    updated: boolean;
};
export type VendorSessionIssueResponse = {
    code: string;
};
export type VendorSessionConsumeResponse = {
    status: "authenticated";
    token: string;
} | {
    status: "verification_required";
    token: string;
    email: string;
};
export type AccountEmailVerificationResponse = {
    email: string;
    status: "verified" | "unverified";
    source: "email" | "google" | null;
};
export type RequestAccountEmailVerificationResponse = {
    status: "requested";
};
export type RequestAccountEmailVerificationInput = { [x: string]: never; };
export type ConfirmAccountEmailVerificationInput = { code: string; };
export type GoogleOneTapTransactionInput = { [x: string]: never; };
export type GoogleOneTapTransactionResponse = { client_id: string; nonce: string; transaction_token: string; expires_at: string; };
export type GoogleOneTapLoginInput = { id_token: string; transaction_token: string; };
