// Generated by scripts/generate-catalog-permission-contracts.cjs. Do not edit.
export type CatalogPermissionMode = "supervised" | "authorized";
export type CatalogPermissionDTO = { seller_id: string; mode: "supervised" | "authorized"; };
export type UpdateCatalogPermission = { mode: "supervised" | "authorized"; };
export type CatalogPermissionListQuery = { seller_ids: string[]; };
export type CatalogPermissionResponse = { catalog_permission: { seller_id: string; mode: "supervised" | "authorized"; }; };
export type CatalogPermissionListResponse = { catalog_permissions: { seller_id: string; mode: "supervised" | "authorized"; }[]; };
