// Generated by scripts/generate-catalog-management-contracts.cjs. Do not edit.
export type AdminCatalogProductManageInput = { expected_updated_at: string; action: "update-content"; content: { title: string; subtitle: string | null; description: string | null; }; } | { expected_updated_at: string; action: "withdraw"; } | { expected_updated_at: string; action: "publish"; };
export type AdminCatalogManagementConflictCode = "catalog_pending_change" | "catalog_product_changed" | "catalog_status_changed";
