// Generated by scripts/generate-catalog-management-contracts.cjs. Do not edit.
export type AdminCatalogProductManageInput = { expected_updated_at: string; action: "update-content"; content: { title: string; subtitle: string | null; description: string | null; }; } | { expected_updated_at: string; action: "withdraw"; } | { expected_updated_at: string; action: "publish"; };
export type AdminCatalogManagementConflictCode = "catalog_pending_change" | "catalog_product_changed" | "catalog_status_changed";
export type ProductLifecycleOperation = "archive" | "deactivate" | "activate";
export type ProductLifecycleState = { can_manage: boolean; can_activate: boolean; status: string; requires_review: boolean; reason: string | null; };
export type ProductLifecycleResult = { operation: "archive" | "deactivate" | "activate"; applied: boolean; product_change_id: string; };
