// Generated by scripts/generate-finance-contracts.cjs. Do not edit.
export type OrderFinanceInput = { action: "cancel" | "refund" | "capture"; note: string; request_id: string; confirm: true; amount?: number | undefined; };
export type OrderFinanceResponse = {
    finance: {
        order_id: string;
        currency_code: string;
        allocated_total: number;
        refunded_total: number;
        refundable_total: number;
        captured_total: number;
        capture: {
            allowed: boolean;
            reason: string | null;
            amount: number;
        };
        cancellation: {
            allowed: boolean;
            reason: string | null;
            refund_amount: number;
        };
        refund: {
            allowed: boolean;
            reason: string | null;
        };
        history: Array<{
            id: string;
            kind: "cancel" | "refund" | "capture";
            amount: number;
            status: "processing" | "complete" | "uncertain";
            note: string;
            created_at: string;
            seller_reversed?: number;
            commission_returned?: number;
        }>;
    };
};
