// Generated by scripts/generate-order-notification-contracts.cjs. Do not edit.
export type VendorOrderNotificationsResponse = { has_pending_orders: boolean; };
export type VendorOrderCompletionResponse = { can_complete: boolean; pickup_fulfillment_ids: string[]; preparation_groups: { shipping_option_id: string | null; is_pickup: boolean; item_ids: string[]; }[]; };
export type AdminNotificationEvent = "applications-changed" | "catalog-changed" | "orders-changed" | "stores-changed" | "finance-reporting-changed";
export type AdminOrderCountResponse = { count: number; };
export type AdminNotificationsResponse = { applications: { status: "ready"; has_pending: boolean; } | { status: "denied"; } | { status: "unavailable"; }; catalog: { status: "ready"; has_pending: boolean; } | { status: "denied"; } | { status: "unavailable"; }; };
