// Generated by scripts/generate-order-tracking-contracts.cjs. Do not edit.
import type { OrderStatus } from "@medusajs/framework/utils";

export type StoreOrderTrackingInput = { token: string; };
export type StoreOrderTrackingResponse = { order: { display_id: number; custom_display_id: string | null; created_at: string; status: OrderStatus; delivery_mode: "unknown" | "pickup" | "shipping" | "mixed"; fulfillment_status: "not_fulfilled" | "partially_fulfilled" | "fulfilled" | "partially_shipped" | "shipped" | "partially_delivered" | "delivered" | "canceled"; currency_code: string; total: number; items: { thumbnail: string | null; id: string; title: string; variant_title: string | null; quantity: number; unit_price: number; detail: { fulfilled_quantity: number | null; shipped_quantity: number | null; delivered_quantity: number | null; } | null; }[]; fulfillments: { id: string; created_at: string | null; delivery_mode: "unknown" | "pickup" | "shipping"; packed_at: string | null; shipped_at: string | null; delivered_at: string | null; canceled_at: string | null; labels: { tracking_number: string | null; tracking_url: string | null; }[]; }[]; }; };
export type StoreOrderTrackingClaimInput = { token: string; };
export type StoreOrderTrackingClaimResponse = { status: "associated"; order_id: string; };
