// Generated by scripts/generate-search-contracts.cjs. Do not edit.
import type { HttpTypes } from "@medusajs/framework/types";

export type StoreSearchProductsInput = { region_id: string; query?: string | undefined; page?: number | undefined; hitsPerPage?: number | undefined; category_ids?: string[] | undefined; seller_ids?: string[] | undefined; min_price?: number | undefined; max_price?: number | undefined; sort?: "relevance" | "price_asc" | "price_desc" | "newest" | undefined; country_code?: "us" | undefined; };
export type SearchFacet = {
    id: string;
    label: string;
    count: number;
};
export type StoreSearchProductsResponse = {
    products: HttpTypes.StoreProduct[];
    nbHits: number;
    page: number;
    nbPages: number;
    hitsPerPage: number;
    facets: {
        categories: SearchFacet[];
        sellers: SearchFacet[];
    };
    price_range: {
        min: number;
        max: number;
    } | null;
    query: string;
};
